Repository Founntain/osuplayer, pull requests merged in 2022-12, with the labels that each got.

#161 Fix some statistics view issues
  OsuPlayer.Extensions/ValueConverters/DecimalFormatter.cs
  OsuPlayer/Views/StatisticsView.axaml
  OsuPlayer/Views/StatisticsViewModel.cs
Labels: enhancement, bugfix

#164 Add some checks to play methods to avoid index out of range
  OsuPlayer.Extensions/NullOrEmptyException.cs
  OsuPlayer/Modules/Audio/Player.cs
  OsuPlayer/Modules/ShuffleImpl/RngHistoryShuffler.cs
Labels: bugfix, refactor

#170 Fix time stamp overlapping with scrollbar in search view
  OsuPlayer/Views/SearchView.axaml
Labels: bugfix

#171 Fixing crash on login window
  OsuPlayer/Windows/LoginWindow.axaml.cs
  OsuPlayer/Windows/MainWindow.axaml.cs
Labels: bugfix, refactor

#172 Make clicking on the song title go to the current song in the list
  OsuPlayer/Styles/HyperlinkButtonStyle.axaml
  OsuPlayer/Views/HomeViewModel.cs
  OsuPlayer/Views/PlayerControlView.axaml
  OsuPlayer/Views/PlayerControlView.axaml.cs
  OsuPlayer/Views/PlaylistViewModel.cs
  OsuPlayer/Views/SearchViewModel.cs
  OsuPlayer/Windows/MainWindow.axaml.cs
Labels: enhancement
