Repository Founntain/osuplayer, pull requests merged in 2022-09, with the labels that each got.

#111 Implemented a crash display when the Application crashes
  .github/workflows/dotnet-publish.yml
  .idea/.idea.OsuPlayer/.idea/avalonia.xml
  OsuPlayer.Base/OsuPlayer.Base.csproj
  OsuPlayer.Base/ViewModels/BaseViewModel.cs
  OsuPlayer.Base/ViewModels/BaseWindowViewModel.cs
  OsuPlayer.Base/ViewModels/ReactiveControl.cs
  OsuPlayer.Base/ViewModels/ReactiveWindow.cs
  OsuPlayer.CrashHandler/.gitignore
  OsuPlayer.CrashHandler/App.axaml
  OsuPlayer.CrashHandler/App.axaml.cs
  OsuPlayer.CrashHandler/MainWindow.axaml
  OsuPlayer.CrashHandler/MainWindow.axaml.cs
  OsuPlayer.CrashHandler/MainWindowViewModel.cs
  OsuPlayer.CrashHandler/OsuPlayer.CrashHandler.csproj
  OsuPlayer.CrashHandler/Program.cs
  OsuPlayer.Extensions/UnhandledExceptionHandler.cs
  OsuPlayer.Network/API/ApiEndpoints/ApiUserEndpoint.cs
  OsuPlayer.sln
  OsuPlayer/Modules/Audio/Player.cs
  OsuPlayer/OsuPlayer.csproj
  OsuPlayer/Program.cs
  OsuPlayer/UI Extensions/MessageBoxViewModel.cs
  OsuPlayer/UI Extensions/MessageBoxWindow.axaml.cs
  OsuPlayer/Views/BlacklistEditorView.axaml.cs
  OsuPlayer/Views/BlacklistEditorViewModel.cs
  OsuPlayer/Views/EditUserViewModel.cs
  OsuPlayer/Views/EqualizerView.axaml.cs
  OsuPlayer/Views/EqualizerViewModel.cs
  OsuPlayer/Views/HomeView.axaml.cs
  OsuPlayer/Views/HomeViewModel.cs
  OsuPlayer/Views/PartyViewModel.cs
  OsuPlayer/Views/PlayerControlView.axaml.cs
  OsuPlayer/Views/PlayerControlViewModel.cs
  OsuPlayer/Views/PlaylistEditorView.axaml.cs
  OsuPlayer/Views/PlaylistEditorViewModel.cs
  OsuPlayer/Views/PlaylistView.axaml.cs
  OsuPlayer/Views/PlaylistViewModel.cs
  OsuPlayer/Views/SearchView.axaml.cs
  OsuPlayer/Views/SearchViewModel.cs
  OsuPlayer/Views/SettingsView.axaml.cs
  OsuPlayer/Views/SettingsViewModel.cs
  OsuPlayer/Views/TopBarView.axaml.cs
  OsuPlayer/Views/TopBarViewModel.cs
  OsuPlayer/Views/UpdateView.axaml.cs
  OsuPlayer/Views/UpdateViewModel.cs
  OsuPlayer/Views/UserView.axaml.cs
  OsuPlayer/Views/UserViewModel.cs
  OsuPlayer/Views/ViewLocator.cs
  OsuPlayer/Windows/CreateProfileWindow.axaml.cs
  OsuPlayer/Windows/CreateProfileWindowViewModel.cs
  OsuPlayer/Windows/LoginWindow.axaml.cs
  OsuPlayer/Windows/LoginWindowViewModel.cs
  OsuPlayer/Windows/MainWindow.axaml.cs
  OsuPlayer/Windows/MainWindowViewModel.cs
Labels: enhancement

#113 Changed DotSettings and Applied new format
  OsuPlayer.Base/OsuPlayer.Base.csproj
  OsuPlayer.Base/ViewModels/ReactiveWindow.cs
  OsuPlayer.CrashHandler/App.axaml
  OsuPlayer.CrashHandler/App.axaml.cs
  OsuPlayer.CrashHandler/MainWindow.axaml
  OsuPlayer.CrashHandler/MainWindow.axaml.cs
  OsuPlayer.CrashHandler/OsuPlayer.CrashHandler.csproj
  OsuPlayer.CrashHandler/Program.cs
  OsuPlayer.Data/OsuPlayer/Classes/AudioDevice.cs
  OsuPlayer.Extensions/Bindables/BindableArray.cs
  OsuPlayer.Extensions/UnhandledExceptionHandler.cs
  OsuPlayer.IO/DbReader/OsuDbReader.cs
  OsuPlayer.IO/Storage/LazerModels/Beatmaps/BeatmapInfo.cs
  OsuPlayer.IO/Storage/LazerModels/Beatmaps/BeatmapMetadata.cs
  OsuPlayer.IO/Storage/LazerModels/Beatmaps/BeatmapSetInfo.cs
  OsuPlayer.IO/Storage/LazerModels/Beatmaps/RulesetInfo.cs
  OsuPlayer.Network/API/ApiEndpoints/ApiUserEndpoint.cs
  OsuPlayer.Network/Discord/DiscordClient.cs
  OsuPlayer.Network/GitHubUpdater.cs
  OsuPlayer.Network/Online/User.cs
  OsuPlayer.sln.DotSettings
  OsuPlayer/Controls/CascadingWrapPanel.cs
  OsuPlayer/Modules/Audio/BassEngine.cs
  OsuPlayer/Modules/Audio/Player.cs
  OsuPlayer/Program.cs
  OsuPlayer/UI Extensions/MessageBoxViewModel.cs
  OsuPlayer/UI Extensions/MessageBoxWindow.axaml
  OsuPlayer/UI Extensions/MessageBoxWindow.axaml.cs
  OsuPlayer/Views/BlacklistEditorViewModel.cs
  OsuPlayer/Views/EditUserView.axaml.cs
  OsuPlayer/Views/EditUserViewModel.cs
  OsuPlayer/Views/EqualizerViewModel.cs
  OsuPlayer/Views/HomeView.axaml
  OsuPlayer/Views/HomeViewModel.cs
  OsuPlayer/Views/PartyView.axaml
  OsuPlayer/Views/PlayerControlView.axaml.cs
  OsuPlayer/Views/PlayerControlViewModel.cs
  OsuPlayer/Views/PlaylistEditorViewModel.cs
  OsuPlayer/Views/PlaylistView.axaml
  OsuPlayer/Views/PlaylistViewModel.cs
  OsuPlayer/Views/SearchViewModel.cs
  OsuPlayer/Views/SettingsViewModel.cs
  OsuPlayer/Views/UpdateView.axaml
  OsuPlayer/Views/UpdateViewModel.cs
  OsuPlayer/Views/UserView.axaml
  OsuPlayer/Views/UserView.axaml.cs
  OsuPlayer/Views/UserViewModel.cs
  OsuPlayer/Windows/CreateProfileWindow.axaml.cs
  OsuPlayer/Windows/LoginWindow.axaml.cs
  OsuPlayer/Windows/MainWindow.axaml.cs
  OsuPlayer/Windows/MainWindowViewModel.cs
Labels: documentation

#126 Colorful Update, ability to change Window Background Color which also works with Mica and AcrylicBlur
  OsuPlayer.Extensions/KnownColors.cs
  OsuPlayer.Extensions/TypeExtensions.cs
  OsuPlayer.IO/Storage/Config/ConfigContainer.cs
  OsuPlayer.sln.DotSettings
  OsuPlayer/App.axaml
  OsuPlayer/UI Extensions/MessageBoxWindow.axaml
  OsuPlayer/Views/BlacklistEditorView.axaml
  OsuPlayer/Views/EditUserView.axaml
  OsuPlayer/Views/HomeView.axaml
  OsuPlayer/Views/PlayerControlView.axaml
  OsuPlayer/Views/PlaylistEditorView.axaml
  OsuPlayer/Views/PlaylistView.axaml
  OsuPlayer/Views/SettingsView.axaml
  OsuPlayer/Views/SettingsViewModel.cs
  OsuPlayer/Views/TopBarView.axaml
  OsuPlayer/Views/UpdateView.axaml
  OsuPlayer/Views/UserView.axaml
  OsuPlayer/Windows/CreateProfileWindow.axaml
  OsuPlayer/Windows/LoginWindow.axaml
  OsuPlayer/Windows/MainWindow.axaml
  OsuPlayer/Windows/MainWindow.axaml.cs
  OsuPlayer/Windows/MainWindowViewModel.cs
Labels: enhancement

#127 Fix patch notes regex bug
  OsuPlayer.Network/GitHubUpdater.cs
  OsuPlayer/Views/SettingsViewModel.cs
Labels: bug

#129 Remove unused delete command causing crash
  .github/workflows/dotnet-publish.yml
Labels: bug

#130 Remove DotNET testing framework package
  .github/workflows/dotnet-publish.yml
  OsuPlayer.Tests/OsuPlayer.Tests.csproj
  OsuPlayer.sln
  OsuPlayer/OsuPlayer.csproj
Labels: dependencies

#133 Fixed missing background in search view also fixed margins for search text
  OsuPlayer/Views/SearchView.axaml
Labels: bug

#134 Selectable font weights and font selection
  OsuPlayer.Data/OsuPlayer/Classes/ConfigStorage.cs
  OsuPlayer.Extensions/Enums/FontWeights.cs
  OsuPlayer.Extensions/TypeExtensions.cs
  OsuPlayer.Extensions/ValueConverters/FontWeightsToFontWeightConverter.cs
  OsuPlayer.IO/Storage/Config/ConfigContainer.cs
  OsuPlayer/App.axaml
  OsuPlayer/Views/BlacklistEditorView.axaml
  OsuPlayer/Views/EditUserView.axaml
  OsuPlayer/Views/EqualizerView.axaml
  OsuPlayer/Views/HomeView.axaml
  OsuPlayer/Views/PartyView.axaml
  OsuPlayer/Views/PlayerControlView.axaml
  OsuPlayer/Views/PlayerControlViewModel.cs
  OsuPlayer/Views/PlaylistEditorView.axaml
  OsuPlayer/Views/PlaylistView.axaml
  OsuPlayer/Views/SearchView.axaml
  OsuPlayer/Views/SettingsView.axaml
  OsuPlayer/Views/SettingsViewModel.cs
  OsuPlayer/Views/TopBarView.axaml
  OsuPlayer/Views/UpdateView.axaml
  OsuPlayer/Views/UserView.axaml
  OsuPlayer/Windows/CreateProfileWindow.axaml
  OsuPlayer/Windows/LoginWindow.axaml
  OsuPlayer/Windows/MainWindow.axaml
  OsuPlayer/Windows/MainWindow.axaml.cs
  OsuPlayer/Windows/MainWindowViewModel.cs
Labels: enhancement

#136 Adds settable accent color and shade generation
  OsuPlayer.Extensions/TypeExtensions.cs
  OsuPlayer.IO/Storage/Config/ConfigContainer.cs
  OsuPlayer/App.axaml
  OsuPlayer/Styles/Accents/AccentColors.axaml
  OsuPlayer/Styles/Accents/BaseDark.axaml
  OsuPlayer/Styles/Accents/FluentControlResourcesDark.axaml
  OsuPlayer/Styles/ColorSetter.cs
  OsuPlayer/Styles/FluentDark.axaml
  OsuPlayer/Styles/SliderStyle.axaml
  OsuPlayer/Views/SettingsView.axaml
  OsuPlayer/Views/SettingsViewModel.cs
  OsuPlayer/Windows/MainWindow.axaml
  OsuPlayer/Windows/MainWindow.axaml.cs
  OsuPlayer/Windows/MainWindowViewModel.cs
Labels: enhancement
