Repository Founntain/osuplayer, pull requests merged in 2022-11, with the labels that each got.

#152 .NET 7 & Updated Dependencies
  .github/workflows/dotnet-publish.yml
  .github/workflows/dotnet.yml
  OsuPlayer.Base/OsuPlayer.Base.csproj
  OsuPlayer.CrashHandler/OsuPlayer.CrashHandler.csproj
  OsuPlayer.Data/OsuPlayer.Data.csproj
  OsuPlayer.Extensions/OsuPlayer.Extensions.csproj
  OsuPlayer.IO/OsuPlayer.IO.csproj
  OsuPlayer.NativeLibs/OsuPlayer.NativeLibs.csproj
  OsuPlayer.Network/OsuPlayer.Network.csproj
  OsuPlayer.Tests/OsuPlayer.Tests.csproj
  OsuPlayer/OsuPlayer.csproj
Labels: enhancement, dependencies

#154 Using switches instead of checkboxes
  OsuPlayer/Views/EqualizerView.axaml
  OsuPlayer/Views/SettingsView.axaml
Labels: enhancement

#155 Make Discord RPC togglable
  OsuPlayer.Data/OsuPlayer/StorageModels/ConfigContainer.cs
  OsuPlayer.Network/Discord/DiscordClient.cs
  OsuPlayer/Modules/Audio/Player.cs
  OsuPlayer/Views/SettingsView.axaml
  OsuPlayer/Views/SettingsViewModel.cs
Labels: enhancement

#156 The funny view
  .idea/.idea.OsuPlayer/.idea/avalonia.xml
  OsuPlayer/OsuPlayer.csproj
  OsuPlayer/Views/SymmetricalView.axaml
  OsuPlayer/Views/SymmetricalView.axaml.cs
  OsuPlayer/Views/SymmetricalViewModel.cs
  OsuPlayer/Views/TopBarView.axaml
  OsuPlayer/Views/TopBarView.axaml.cs
  OsuPlayer/Windows/MainWindowViewModel.cs
Labels: enhancement

#158 Fix invalid songs in playlist crashing player
  OsuPlayer.IO/Importer/ISongSourceProvider.cs
  OsuPlayer.Network/Discord/DiscordClient.cs
  OsuPlayer/Modules/Audio/Player.cs
  OsuPlayer/Modules/Services/OsuSongSourceProvider.cs
  OsuPlayer/ValueConverters/PlaylistValueConverter.cs
  OsuPlayer/Views/PlaylistView.axaml.cs
  OsuPlayer/Views/PlaylistViewModel.cs
  OsuPlayer/Views/SettingsViewModel.cs
Labels: bugfix

#159 Fix storables writing crash if not accessible and retry 3 times
  OsuPlayer.IO/Storage/Playlists/PlaylistManager.cs
  OsuPlayer.IO/Storage/Storable.cs
Labels: bugfix
