Repository Founntain/osuplayer, pull requests merged in 2022-06, with the labels that each got.

#83 Adds own publish runner for native builds
  .github/workflows/dotnet-publish.yml
Labels: enhancement

#84 Remove "OsuPlayer" switch causing error
  .github/workflows/dotnet-publish.yml
Labels: enhancement

#85 Updated NuGet Packages
  OsuPlayer.Data/OsuPlayer.Data.csproj
  OsuPlayer.Extensions/OsuPlayer.Extensions.csproj
  OsuPlayer.IO/OsuPlayer.IO.csproj
  OsuPlayer.Network/OsuPlayer.Network.csproj
  OsuPlayer.Tests/OsuPlayer.Tests.csproj
  OsuPlayer/OsuPlayer.csproj
Labels: enhancement, dependencies

#92 Fix crashing if no playlist is selected on shuffle
  OsuPlayer/Modules/Audio/Player.cs
Labels: bug

#96 Make playlists easier and obvious to play
  OsuPlayer.IO/Storage/Config/ConfigContainer.cs
  OsuPlayer/Modules/Audio/Player.cs
  OsuPlayer/Views/EditUserView.axaml.cs
  OsuPlayer/Views/PlaylistView.axaml
  OsuPlayer/Views/PlaylistView.axaml.cs
  OsuPlayer/Views/SettingsView.axaml
  OsuPlayer/Views/SettingsViewModel.cs
  OsuPlayer/Windows/MainWindow.axaml.cs
Labels: enhancement

#101 Add search box for songs in playlist view
  OsuPlayer/Views/PlaylistView.axaml
  OsuPlayer/Views/PlaylistViewModel.cs
Labels: enhancement
