Repository Founntain/osuplayer, pull requests merged in 2022-04, with the labels that each got.

#35 Add playlist only mode
  OsuPlayer.Data/OsuPlayer/Enums/RepeatMode.cs
  OsuPlayer.Extensions/Extensions.cs
  OsuPlayer.Extensions/ValueConverters/RepeatConverter.cs
  OsuPlayer.Tests/ValueConverterTests/RepeatConverterTests.cs
  OsuPlayer/Modules/Audio/Player.cs
  OsuPlayer/Views/PlayerControlView.axaml
  OsuPlayer/Views/PlayerControlView.axaml.cs
  OsuPlayer/Views/PlayerControlViewModel.cs
  OsuPlayer/Views/PlaylistEditorView.axaml.cs
  OsuPlayer/Views/PlaylistEditorViewModel.cs
  OsuPlayer/Views/PlaylistViewModel.cs
Labels: enhancement

#47 Add different song sorting modes
  OsuPlayer.Data/OsuPlayer/Classes/LastPlayedSongModel.cs
  OsuPlayer.Data/OsuPlayer/Enums/SortingMode.cs
  OsuPlayer.Extensions/Extensions.cs
  OsuPlayer.Extensions/ValueConverters/RepeatConverter.cs
  OsuPlayer.IO/DbReader/Collection.cs
  OsuPlayer.IO/DbReader/DataModels/DbMapEntry.cs
  OsuPlayer.IO/DbReader/DataModels/DbMapEntryBase.cs
  OsuPlayer.IO/DbReader/DataModels/RealmMapEntry.cs
  OsuPlayer.IO/DbReader/OsuDbReader.cs
  OsuPlayer.IO/DbReader/RealmReader.cs
  OsuPlayer.IO/SongImporter.cs
  OsuPlayer.IO/Storage/Config/Config.cs
  OsuPlayer.IO/Storage/Config/ConfigContainer.cs
  OsuPlayer/Modules/Audio/BassEngine.cs
  OsuPlayer/Modules/Audio/Player.cs
  OsuPlayer/Views/HomeView.axaml.cs
  OsuPlayer/Views/HomeViewModel.cs
  OsuPlayer/Views/PlaylistEditorViewModel.cs
  OsuPlayer/Views/PlaylistView.axaml.cs
  OsuPlayer/Views/SettingsView.axaml
  OsuPlayer/Views/SettingsView.axaml.cs
  OsuPlayer/Views/SettingsViewModel.cs
  OsuPlayer/Windows/LoginWindow.axaml.cs
  OsuPlayer/Windows/MainWindow.axaml.cs
Labels: documentation, enhancement

#50 Adds more documentation to some classes
  OsuPlayer.Extensions/Extensions.cs
  OsuPlayer.Extensions/UnhandledExceptionHandler.cs
  OsuPlayer.IO/DbReader/DataModels/DbMapEntryBase.cs
  OsuPlayer.IO/DbReader/DataModels/IMapEntry.cs
  OsuPlayer.IO/DbReader/DataModels/IMapEntryBase.cs
  OsuPlayer.IO/DbReader/DataModels/RealmMapEntryBase.cs
  OsuPlayer.IO/Storage/Playlists/PlaylistManager.cs
  OsuPlayer.Network/API/ApiEndpoints/ApiBase.cs
  OsuPlayer.Network/API/ApiEndpoints/ApiUserEndpoint.cs
  OsuPlayer.Network/API/ApiLanguage.cs
  OsuPlayer.Network/Constants.cs
  OsuPlayer.Network/Online/User.cs
  OsuPlayer.Network/Online/UserColors.cs
  OsuPlayer.Network/OsuPlayer.Network.csproj
  OsuPlayer/Modules/Audio/BassEngine.cs
  OsuPlayer/Modules/Audio/Player.cs
  OsuPlayer/UI Extensions/MessageBox.cs
  OsuPlayer/ValueConverters/PlaylistValueConverter.cs
  OsuPlayer/Views/EditUserView.axaml.cs
  OsuPlayer/Views/ReactivePlayerControl.cs
  OsuPlayer/Windows/ReactivePlayerWindow.cs
Labels: documentation

#51 Collection importer
  OsuPlayer.IO/DbReader/Collection.cs
  OsuPlayer.IO/DbReader/OsuCollectionReader.cs
  OsuPlayer.IO/DbReader/OsuDbReader.cs
  OsuPlayer.IO/DbReader/RealmReader.cs
  OsuPlayer.IO/SongImporter.cs
  OsuPlayer.IO/Storage/Playlists/PlaylistManager.cs
  OsuPlayer.Network/Online/User.cs
  OsuPlayer.sln.DotSettings
  OsuPlayer/Modules/Audio/BassEngine.cs
  OsuPlayer/Modules/Audio/Player.cs
  OsuPlayer/UI Extensions/MessageBox.cs
  OsuPlayer/ValueConverters/PlaylistValueConverter.cs
  OsuPlayer/Views/SettingsView.axaml
  OsuPlayer/Views/SettingsView.axaml.cs
  OsuPlayer/Views/SettingsViewModel.cs
  OsuPlayer/Windows/ReactivePlayerWindow.cs
Labels: documentation, enhancement
