Repository Founntain/osuplayer, pull requests merged in 2023-11, with the labels that each got.

#239 Discord Client as Service and fixing unnessary thumbnail requests
  OsuPlayer.Interfaces/OsuPlayer.Interfaces.csproj
  OsuPlayer.Interfaces/Service/IDiscordService.cs
  OsuPlayer.Network/OsuPlayer.Network.csproj
  OsuPlayer.Services/DiscordService.cs
  OsuPlayer.Services/OsuPlayer.Services.csproj
  OsuPlayer.Services/OsuPlayerService.cs
  OsuPlayer.Services/ProfileManagerService.cs
  OsuPlayer/Modules/Audio/Player.cs
  OsuPlayer/Program.cs
  OsuPlayer/Views/UserViewModel.cs
Labels: bugfix, refactor

#242 Remade UI for the not logged in part
  OsuPlayer/Views/HomeSubViews/HomeUserPanelView.axaml
Labels: enhancement, bugfix, UI

#247 Cleanup after Avalonia 11 Merge and smaller fixes
  OsuPlayer.CrashHandler/App.axaml
  OsuPlayer.CrashHandler/CrashHandlerMainWindow.axaml.cs
  OsuPlayer.CrashHandler/OsuPlayer.CrashHandler.csproj
  OsuPlayer.Data/DataModels/Interfaces/IUser.cs
  OsuPlayer.Data/DataModels/User.cs
  OsuPlayer.Data/OsuPlayer.Data.csproj
  OsuPlayer.Data/OsuPlayer/StorageModels/ConfigContainer.cs
  OsuPlayer.Extensions/FilePickerFileTypesExtensions.cs
  OsuPlayer.Extensions/OsuPlayer.Extensions.csproj
  OsuPlayer.IO/OsuPlayer.IO.csproj
  OsuPlayer.Interfaces/OsuPlayer.Interfaces.csproj
  OsuPlayer.Network/OsuPlayer.Network.csproj
  OsuPlayer.Services/OsuPlayer.Services.csproj
  OsuPlayer.Tests/NetworkTests/OnlineTests.cs
  OsuPlayer.Tests/OsuPlayer.Tests.csproj
  OsuPlayer/Modules/Audio/Engine/BassEngine.cs
  OsuPlayer/Modules/Audio/Interfaces/IAudioEngine.cs
  OsuPlayer/Modules/Audio/Player.cs
  OsuPlayer/Modules/FluentReactiveWindow.cs
  OsuPlayer/OsuPlayer.csproj
  OsuPlayer/Styles/ColorSetter.cs
  OsuPlayer/Views/EditUserView.axaml
  OsuPlayer/Views/EditUserView.axaml.cs
  OsuPlayer/Views/ExportSongsView.axaml.cs
  OsuPlayer/Views/HomeSubViews/HomeUserPanelView.axaml
  OsuPlayer/Views/HomeView.axaml
  OsuPlayer/Views/PlayerControlView.axaml.cs
  OsuPlayer/Views/SettingsView.axaml
  OsuPlayer/Views/SettingsView.axaml.cs
  OsuPlayer/Views/SettingsViewModel.cs
  OsuPlayer/Windows/FluentAppWindow.axaml
  OsuPlayer/Windows/FluentAppWindow.axaml.cs
  OsuPlayer/Windows/FluentAppWindowViewModel.cs
  OsuPlayer/Windows/MainWindow.axaml
  OsuPlayer/Windows/MainWindow.axaml.cs
  OsuPlayer/Windows/MainWindowViewModel.cs
  OsuPlayer/Windows/Miniplayer.axaml.cs
Labels: bugfix, refactor

#248 Disabled some settings as they aren't support right now
  OsuPlayer/Views/SettingsView.axaml
  OsuPlayer/Windows/FluentAppWindow.axaml.cs
Labels: bugfix, refactor

#250 Fix import failing in different scenarios
  OsuPlayer.IO/FodyWeavers.xml
  OsuPlayer.IO/FodyWeavers.xsd
  OsuPlayer.IO/OsuPlayer.IO.csproj
  OsuPlayer.IO/Realm.Fody.dll
  OsuPlayer.IO/Realm.PlatformHelpers.dll
  OsuPlayer.IO/Realm.dll
  OsuPlayer/Views/EditUserView.axaml.cs
  OsuPlayer/Views/ExportSongsView.axaml.cs
  OsuPlayer/Views/SettingsView.axaml.cs
Labels: dependencies, bugfix

#253 Fixed Linux Background Problems, because of Acrylic Border
  OsuPlayer/Views/SettingsViewModel.cs
  OsuPlayer/Windows/FluentAppWindow.axaml
  OsuPlayer/Windows/FluentAppWindow.axaml.cs
  OsuPlayer/Windows/FluentAppWindowViewModel.cs
Labels: bugfix

#255 Fixes miniplayer opening reverting song to 1:40 if song is after that point
  OsuPlayer/Windows/Miniplayer.axaml
  OsuPlayer/Windows/Miniplayer.axaml.cs
Labels: bugfix

#259 Changed Login, CreateProfile and MiniPlayer to FluentReactiveWindow
  OsuPlayer/Views/PlayerControlView.axaml
  OsuPlayer/Windows/CreateProfileWindow.axaml.cs
  OsuPlayer/Windows/LoginWindow.axaml
  OsuPlayer/Windows/LoginWindow.axaml.cs
  OsuPlayer/Windows/Miniplayer.axaml
  OsuPlayer/Windows/Miniplayer.axaml.cs
Labels: refactor

#258 Displaying donator features
  OsuPlayer.Data/DataModels/Interfaces/IUser.cs
  OsuPlayer.Data/DataModels/User.cs
  OsuPlayer/Views/HomeSubViews/HomeUserPanelView.axaml
  OsuPlayer/Views/UserView.axaml
Labels: enhancement, UI
