Repository Founntain/osuplayer, pull requests merged in 2023-05, with the labels that each got.

#195 Remove loading of unavailable fonts
  OsuPlayer/App.axaml
  OsuPlayer/OsuPlayer.csproj
  OsuPlayer/Resources/Fonts/Montserrat-VariableFont_wght.ttf
Labels: bugfix

#196 Make Storable containers static to avoid race conditions & Cleanup
  OsuPlayer.Data/OsuPlayer/Enums/FontWeights.cs
  OsuPlayer.Data/OsuPlayer/Enums/KnownColors.cs
  OsuPlayer.Data/OsuPlayer/StorageModels/ConfigContainer.cs
  OsuPlayer.Extensions/FontWeightExtensions.cs
  OsuPlayer.Extensions/KnownColorsExtensions.cs
  OsuPlayer.Extensions/UnhandledExceptionHandler.cs
  OsuPlayer.IO/DbReader/DataModels/DbMapEntry.cs
  OsuPlayer.IO/DbReader/DataModels/RealmMapEntryBase.cs
  OsuPlayer.IO/Storage/Blacklist/Blacklist.cs
  OsuPlayer.IO/Storage/Config/Config.cs
  OsuPlayer.IO/Storage/Equalizer/EqStorage.cs
  OsuPlayer.IO/Storage/Playlists/PlaylistStorage.cs
  OsuPlayer.Network/API/NewApiEndpoints/NewApiBase.cs
  OsuPlayer.Network/API/Service/AbstractApiBase.cs
  OsuPlayer.Network/API/Service/Endpoints/Nortfox.cs
  OsuPlayer.Network/API/Service/Endpoints/NorthFox.Activity.cs
  OsuPlayer.Network/API/Service/Endpoints/NorthFox.ApiStatistics.cs
  OsuPlayer.Network/API/Service/Endpoints/NorthFox.Badge.cs
  OsuPlayer.Network/API/Service/Endpoints/NorthFox.Beatmap.cs
  OsuPlayer.Network/API/Service/Endpoints/NorthFox.Event.cs
  OsuPlayer.Network/API/Service/Endpoints/NorthFox.User.cs
  OsuPlayer.Network/API/Service/Endpoints/NorthFox.UserStatistics.cs
  OsuPlayer.Network/Online/ProfileManager.cs
  OsuPlayer.Network/Online/User.cs
  OsuPlayer/Modules/Audio/Engine/BassEngine.cs
  OsuPlayer/Modules/Audio/Player.cs
  OsuPlayer/Modules/Services/ApiStatisticsProvider.cs
  OsuPlayer/Modules/Services/ShuffleServiceProvider.cs
  OsuPlayer/OsuPlayer.csproj
  OsuPlayer/Program.cs
  OsuPlayer/UI Extensions/MessageBoxWindow.axaml
  OsuPlayer/UI Extensions/MessageBoxWindow.axaml.cs
  OsuPlayer/Views/EditUserView.axaml.cs
  OsuPlayer/Views/EditUserViewModel.cs
  OsuPlayer/Views/PlayerControlViewModel.cs
  OsuPlayer/Views/SettingsView.axaml
  OsuPlayer/Views/SettingsView.axaml.cs
  OsuPlayer/Views/SettingsViewModel.cs
  OsuPlayer/Views/StatisticsViewModel.cs
  OsuPlayer/Views/UserView.axaml
  OsuPlayer/Views/UserView.axaml.cs
  OsuPlayer/Views/UserViewModel.cs
  OsuPlayer/Windows/CreateProfileWindow.axaml
  OsuPlayer/Windows/CreateProfileWindow.axaml.cs
  OsuPlayer/Windows/LoginWindow.axaml
  OsuPlayer/Windows/LoginWindow.axaml.cs
  OsuPlayer/Windows/MainWindow.axaml.cs
  OsuPlayer/Windows/MainWindowViewModel.cs
  OsuPlayer/Windows/Miniplayer.axaml
  OsuPlayer/Windows/Miniplayer.axaml.cs
  OsuPlayer/Windows/MiniplayerViewModel.cs
Labels: enhancement, refactor

#197 Fixes the pitch config not respected on new song
  OsuPlayer/Modules/Audio/Engine/BassEngine.cs
Labels: bugfix

#198 Selectable audio device
  OsuPlayer.Data/OsuPlayer/StorageModels/ConfigContainer.cs
  OsuPlayer/Modules/Audio/Engine/BassEngine.cs
  OsuPlayer/Modules/Audio/Interfaces/ISettableAudioDevices.cs
  OsuPlayer/Views/SettingsView.axaml
  OsuPlayer/Views/SettingsViewModel.cs
Labels: enhancement

#200 Fixes crash when importing newest lazer realm file
  OsuPlayer.IO/DbReader/DataModels/RealmMapEntryBase.cs
  OsuPlayer.IO/DbReader/RealmReader.cs
  OsuPlayer.IO/Realm.Fody.dll
  OsuPlayer.IO/Realm.dll
Labels: dependencies, bugfix

#201 Adding bitmap blur and make miniplayer background blurred
  .idea/.idea.OsuPlayer/.idea/avalonia.xml
  OsuPlayer/Modules/BitmapExtensions.cs
  OsuPlayer/OsuPlayer.csproj
  OsuPlayer/Views/PlayerControlView.axaml.cs
  OsuPlayer/Windows/FullscreenWindow.axaml
  OsuPlayer/Windows/FullscreenWindow.axaml.cs
  OsuPlayer/Windows/FullscreenWindowViewModel.cs
  OsuPlayer/Windows/MainWindow.axaml
  OsuPlayer/Windows/MainWindow.axaml.cs
  OsuPlayer/Windows/Miniplayer.axaml.cs
  OsuPlayer/Windows/MiniplayerViewModel.cs
Labels: enhancement, bugfix
