Repository Founntain/osuplayer, pull requests merged in 2023-12, with the labels that each got.

#261 Updated Dependencies
  OsuPlayer.CrashHandler/OsuPlayer.CrashHandler.csproj
  OsuPlayer.Data/OsuPlayer.Data.csproj
  OsuPlayer.Extensions/OsuPlayer.Extensions.csproj
  OsuPlayer.IO/OsuPlayer.IO.csproj
  OsuPlayer.Interfaces/OsuPlayer.Interfaces.csproj
  OsuPlayer.Network/OsuPlayer.Network.csproj
  OsuPlayer.Services/OsuPlayer.Services.csproj
  OsuPlayer.Tests/FormatTimeTests.cs
  OsuPlayer.Tests/IOTests/ConfigTests.cs
  OsuPlayer.Tests/IOTests/PlaylistStorageTests.cs
  OsuPlayer.Tests/IOTests/PlaylistTests.cs
  OsuPlayer.Tests/NetworkTests/OnlineTests.cs
  OsuPlayer.Tests/NetworkTests/PasswordManagerTests.cs
  OsuPlayer.Tests/OsuPlayer.Tests.csproj
  OsuPlayer.Tests/ValueConverterTests/GridFormatterTests.cs
  OsuPlayer.Tests/ValueConverterTests/PlayPauseConverterTests.cs
  OsuPlayer.Tests/ValueConverterTests/RepeatConverterTests.cs
  OsuPlayer.Tests/ValueConverterTests/SettingsUserConverterTests.cs
  OsuPlayer.Tests/ValueConverterTests/ShuffleConverterTests.cs
  OsuPlayer.Tests/ValueConverterTests/SourceListValueConverterTests.cs
  OsuPlayer.Tests/ValueConverterTests/VolumeConverterTests.cs
  OsuPlayer/OsuPlayer.csproj
Labels: dependencies

#262 Add toggleable audio normalization
  OsuPlayer.Data/OsuPlayer/StorageModels/ConfigContainer.cs
  OsuPlayer/Modules/Audio/Engine/BassEngine.cs
  OsuPlayer/Views/SettingsView.axaml
  OsuPlayer/Views/SettingsViewModel.cs
Labels: enhancement

#264 Implementation of Audio Visualizer
  .idea/.idea.OsuPlayer/.idea/avalonia.xml
  OsuPlayer.Data/OsuPlayer/StorageModels/ConfigContainer.cs
  OsuPlayer/Modules/Audio/Engine/BassEngine.cs
  OsuPlayer/Modules/Audio/Interfaces/IAudioEngine.cs
  OsuPlayer/OsuPlayer.csproj
  OsuPlayer/Views/CustomControls/AudioVisualizerView.axaml
  OsuPlayer/Views/CustomControls/AudioVisualizerView.axaml.cs
  OsuPlayer/Views/CustomControls/AudioVisualizerViewModel.cs
  OsuPlayer/Views/HomeSubViews/HomeUserPanelView.axaml
  OsuPlayer/Views/PlayerControlView.axaml
  OsuPlayer/Views/PlayerControlView.axaml.cs
  OsuPlayer/Views/PlayerControlViewModel.cs
  OsuPlayer/Views/SettingsView.axaml
  OsuPlayer/Views/SettingsViewModel.cs
  OsuPlayer/Windows/FluentAppWindow.axaml.cs
  OsuPlayer/Windows/FluentAppWindowViewModel.cs
  OsuPlayer/Windows/Miniplayer.axaml
  OsuPlayer/Windows/Miniplayer.axaml.cs
  OsuPlayer/Windows/MiniplayerViewModel.cs
Labels: enhancement, UI

#265 Changed possible min and max value for playbackspeed
  OsuPlayer/Views/PlayerControlView.axaml
Labels: enhancement, UI
