Repository Founntain/osuplayer, pull requests merged in 2023-03, with the labels that each got.

#182 Settings UI redesign
  .idea/.idea.OsuPlayer/.idea/avalonia.xml
  OsuPlayer.Network/API/Service/AbstractApiBase.cs
  OsuPlayer.sln.DotSettings
  OsuPlayer/Controls/Enums/SettingsDisplayerCornerBehaviour.cs
  OsuPlayer/Controls/Interfaces/ISettingsDisplayer.cs
  OsuPlayer/Controls/SettingsDisplayer.axaml
  OsuPlayer/Controls/SettingsDisplayer.axaml.cs
  OsuPlayer/Controls/SettingsTitleDisplayer.axaml
  OsuPlayer/Controls/SettingsTitleDisplayer.axaml.cs
  OsuPlayer/OsuPlayer.csproj
  OsuPlayer/Views/EditUserView.axaml.cs
  OsuPlayer/Views/SettingsView.axaml
  OsuPlayer/Views/SettingsViewModel.cs
Labels: enhancement, refactor

#184 Fixed Background not showing on first miniplayer start
  OsuPlayer/Windows/Miniplayer.axaml.cs
  OsuPlayer/Windows/MiniplayerViewModel.cs
Labels: enhancement, bugfix

#187 Fixed Crash when BackgroundFinder couldn't find a part of the path
  OsuPlayer.IO/DbReader/DataModels/DbMapEntry.cs
Labels: bugfix

#188 Update dependencies
  OsuPlayer.Base/OsuPlayer.Base.csproj
  OsuPlayer.CrashHandler/OsuPlayer.CrashHandler.csproj
  OsuPlayer.Data/OsuPlayer.Data.csproj
  OsuPlayer.Extensions/OsuPlayer.Extensions.csproj
  OsuPlayer.IO/OsuPlayer.IO.csproj
  OsuPlayer.Network/OsuPlayer.Network.csproj
  OsuPlayer.Tests/OsuPlayer.Tests.csproj
  OsuPlayer/OsuPlayer.csproj
Labels: dependencies
