Repository Founntain/osuplayer, pull requests merged in 2023-10, with the labels that each got.

#231 Unified all views
  OsuPlayer/Views/BlacklistEditorView.axaml
  OsuPlayer/Views/EditUserView.axaml
  OsuPlayer/Views/EqualizerView.axaml
  OsuPlayer/Views/HomeSubViews/HomeUserPanelView.axaml
  OsuPlayer/Views/HomeView.axaml
  OsuPlayer/Views/PlaylistEditorView.axaml
  OsuPlayer/Views/PlaylistView.axaml
  OsuPlayer/Views/SearchView.axaml
  OsuPlayer/Views/StatisticsView.axaml
  OsuPlayer/Views/UserView.axaml
Labels: enhancement

#230 Playhistory View
  .idea/.idea.OsuPlayer/.idea/avalonia.xml
  .idea/.idea.OsuPlayer/.idea/dataSources.xml
  OsuPlayer.IO/DbReader/DataModels/DbMapEntry.cs
  OsuPlayer.IO/DbReader/DataModels/DbMapEntryBase.cs
  OsuPlayer.IO/DbReader/DataModels/Extensions/HistoricalMapEntry.cs
  OsuPlayer.IO/DbReader/DataModels/Extensions/HistoricalMapEntryComparer.cs
  OsuPlayer.IO/DbReader/DataModels/RealmMapEntry.cs
  OsuPlayer.IO/DbReader/DataModels/RealmMapEntryBase.cs
  OsuPlayer.IO/DbReader/Interfaces/IDatabaseReader.cs
  OsuPlayer.IO/DbReader/Interfaces/IMapEntry.cs
  OsuPlayer.IO/DbReader/Interfaces/IMapEntryBase.cs
  OsuPlayer.IO/DbReader/OsuDbReader.cs
  OsuPlayer.IO/DbReader/RealmReader.cs
  OsuPlayer.IO/Importer/ISongSourceProvider.cs
  OsuPlayer.IO/Importer/SongImporter.cs
  OsuPlayer.IO/Storage/Blacklist/Blacklist.cs
  OsuPlayer.IO/Storage/Playlists/PlaylistManager.cs
  OsuPlayer/Modules/Audio/Engine/BassEngine.cs
  OsuPlayer/Modules/Audio/Interfaces/ICommonFeatures.cs
  OsuPlayer/Modules/Audio/Interfaces/IPlayer.cs
  OsuPlayer/Modules/Audio/Player.cs
  OsuPlayer/Modules/Audio/WindowsMediaTransportControls.cs
  OsuPlayer/Modules/Services/HistoryProvider.cs
  OsuPlayer/Modules/Services/IHistoryProvider.cs
  OsuPlayer/Modules/Services/ISortProvider.cs
  OsuPlayer/Modules/Services/ObservableSorter.cs
  OsuPlayer/Modules/Services/OsuSongSourceProvider.cs
  OsuPlayer/Modules/Services/SortProvider.cs
  OsuPlayer/OsuPlayer.csproj
  OsuPlayer/Program.cs
  OsuPlayer/Views/BlacklistEditorView.axaml
  OsuPlayer/Views/BlacklistEditorView.axaml.cs
  OsuPlayer/Views/BlacklistEditorViewModel.cs
  OsuPlayer/Views/ExportSongsView.axaml
  OsuPlayer/Views/ExportSongsView.axaml.cs
  OsuPlayer/Views/ExportSongsViewModel.cs
  OsuPlayer/Views/HomeView.axaml
  OsuPlayer/Views/HomeView.axaml.cs
  OsuPlayer/Views/HomeViewModel.cs
  OsuPlayer/Views/PlayHistoryView.axaml
  OsuPlayer/Views/PlayHistoryView.axaml.cs
  OsuPlayer/Views/PlayHistoryViewModel.cs
  OsuPlayer/Views/PlayerControlViewModel.cs
  OsuPlayer/Views/PlaylistEditorView.axaml
  OsuPlayer/Views/PlaylistEditorView.axaml.cs
  OsuPlayer/Views/PlaylistEditorViewModel.cs
  OsuPlayer/Views/PlaylistView.axaml
  OsuPlayer/Views/PlaylistView.axaml.cs
  OsuPlayer/Views/PlaylistViewModel.cs
  OsuPlayer/Views/SearchView.axaml
  OsuPlayer/Views/SearchView.axaml.cs
  OsuPlayer/Views/SearchViewModel.cs
  OsuPlayer/Views/SettingsView.axaml
  OsuPlayer/Views/SettingsView.axaml.cs
  OsuPlayer/Windows/ExportSongsProcessWindow.axaml.cs
  OsuPlayer/Windows/ExportSongsProcessWindowViewModel.cs
  OsuPlayer/Windows/FullscreenWindowViewModel.cs
  OsuPlayer/Windows/MainWindowViewModel.cs
  OsuPlayer/Windows/MiniplayerViewModel.cs
Labels: enhancement

#232 Brought the Settings view to the current ui scheme that we use
  OsuPlayer.CrashHandler/OsuPlayer.CrashHandler.csproj
  OsuPlayer.Data/OsuPlayer.Data.csproj
  OsuPlayer.Extensions/OsuPlayer.Extensions.csproj
  OsuPlayer.IO/OsuPlayer.IO.csproj
  OsuPlayer.Network/OsuPlayer.Network.csproj
  OsuPlayer.Tests/OsuPlayer.Tests.csproj
  OsuPlayer/OsuPlayer.csproj
  OsuPlayer/Views/SettingsView.axaml
Labels: enhancement, dependencies, UI

#236 Fix exporting not recognizing file formats different than mp3
  OsuPlayer.NativeLibs/OsuPlayer.NativeLibs.csproj
  OsuPlayer.NativeLibs/docs/README.md
  OsuPlayer.NativeLibs/runtimes/linux-x64/native/libbassenc.so
  OsuPlayer.NativeLibs/runtimes/linux-x64/native/libbassenc_mp3.so
  OsuPlayer.NativeLibs/runtimes/linux-x86/native/libbassenc.so
  OsuPlayer.NativeLibs/runtimes/linux-x86/native/libbassenc_mp3.so
  OsuPlayer.NativeLibs/runtimes/osx-x64/native/libbassenc.dylib
  OsuPlayer.NativeLibs/runtimes/osx-x64/native/libbassenc_mp3.dylib
  OsuPlayer.NativeLibs/runtimes/win-x64/native/bassenc.dll
  OsuPlayer.NativeLibs/runtimes/win-x64/native/bassenc_mp3.dll
  OsuPlayer.NativeLibs/runtimes/win-x86/native/bassenc.dll
  OsuPlayer.NativeLibs/runtimes/win-x86/native/bassenc_mp3.dll
  OsuPlayer/OsuPlayer.csproj
  OsuPlayer/Windows/ExportSongsProcessWindow.axaml.cs
Labels: enhancement, bugfix
